### ISSUE TITLE
Trouble installing pyrealsense from source

### ISSUE THREAD

**Issue by scaldara55** [toinsson/pyrealsense#20]
| Required Info  |   |
|---|---|
| Camera Model | R200 | 
| Firmware Version | 1.0.72.06 | 
| Operating System & Version | macOS Sierra Version 10.12.4 (16E195)  |
| librealsense version | 1.12.1  |
| pyrealsense version | 1.4  |

I'm trying to install pyrealsense from source.  I run  python setup.py install and that works fine.

Using /Users/scaldara/.virtualenvs/pyrs2.7-steve/lib/python2.7/site-packages
Finished processing dependencies for pyrealsense==1.4

I then start up python and do an import pyrealsense as pyrs

It comes up with this error.

(pyrs2.7-steve) 7831c1c083a2:pyrealsense scaldara$ python
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrealsense as pyrs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyrealsense/__init__.py", line 11, in <module>
    from .utils import pp, _check_error
  File "pyrealsense/utils.py", line 7, in <module>
    from .importlib import lrs
  File "pyrealsense/importlib.py", line 25, in <module>
    rsutilwrapper = ctypes.CDLL(_find_extension_name())
  File "pyrealsense/importlib.py", line 23, in _find_extension_name
    return os.path.join(dirname, f_name)
UnboundLocalError: local variable 'f_name' referenced before assignment
>>> 

With a little bit of poking around the failure.  It's looking for a filename that ends in ".so" and the directory that it is looking in is "pyrealsense"

**Comment by scaldara55** [comment]
I searched around and found: https://github.com/toinsson/pyrealsense/issues/10

In it, toinsson said:
"You should import the library outside of the source directory, otherwise you won't see the compiled file."

This was the cause of my problem.
